Sunbird RC: Starter pack for location master
Code4GovTech/c4gt-milestones pull request #14
Opened 2023-07-13 14:05 UTC by anmode

## Project

Starter pack for location master

### Changes

What was updated (new pages, weekly update, etc.)

### Notes

If there are any further notes.

2023-07-14 10:22 UTC, photon0205 requested changes
change the author in every week's file to your name

2023-07-14 10:22 UTC, photon0205 commented on docs/2023/Sunbird RC/Starter pack location master/index.md
> +[GitHub](www.github.com/anmode)
add https links instead of this in linkedin and github

2023-07-15 15:11 UTC, photon0205 approved these changes

2023-07-15 15:15 UTC, anmode commented
thanks @photon0205

2023-07-16 11:33 UTC, claddyk reviewed
Lgtm

2023-07-16 11:33 UTC, claddyk commented on docs/2023/Sunbird RC/Starter pack location master/index.md
> +[GitHub](https://www.github.com/anmode)
nit:
```bash
- [Email](mailto:anmol2002.aa1@gmail.com)
- [Linked In](https://www.linkedin.com/in/anmode/)
- [GitHub](https://www.github.com/anmode)
```

2023-07-16 16:20 UTC, merged