Initial commit
Code4GovTech/c4gt-milestones pull request #15
Opened 2023-07-13 14:05 UTC by gupta-arpan

## Project

Sunbird-inQuiry

### Changes

Updated Name

### Notes

If there are any further notes.

2023-07-14 10:36 UTC, photon0205 requested changes

2023-07-14 10:36 UTC, photon0205 commented on yarn.lock
remove this `yarn.lock` file

2023-07-14 10:36 UTC, photon0205 commented on .gitignore
remove yarn.lock from `.gitignore` and keep it unchanged

2023-07-14 11:26 UTC, gupta-arpan commented on .gitignore
> remove yarn.lock from `.gitignore` and keep it unchanged

Donem kindly check

2023-07-15 06:46 UTC, photon0205 commented on .gitignore
@gupta-arpan do one thing, download the yarn.lock file from the repo and copy and paste it as it is in the directory and then then commit it in, as i meant that it should not be tracked, not to completely delete it.

2023-07-15 07:24 UTC, gupta-arpan commented on .gitignore
> @gupta-arpan do one thing, download the yarn.lock file from the repo and copy and paste it as it is in the directory and then then commit it in, as i meant that it should not be tracked, not to completely delete it.

Done, kindly look

2023-07-15 07:25 UTC, photon0205 approved these changes

2023-07-18 05:57 UTC, Apoorvgarg-creator approved these changes

2023-07-18 05:57 UTC, merged