1stand2ndweekUpdates
Code4GovTech/c4gt-milestones pull request #184
Opened 2023-07-19 08:12 UTC by Prakhar-commits

Quiz Creator

This PR consists of the updates for the first two weeks of the C4GT program

It consists of the weekly updates

2023-07-19 09:25 UTC, Shruti3004 requested changes

2023-07-19 09:25 UTC, Shruti3004 commented on docs/2023/Quiz Creator/Quiz Creator/index.md
> +Rishabh Jain
Hey @Prakhar-commits please add your name here

2023-07-19 09:25 UTC, Shruti3004 commented on docs/2023/Quiz Creator/Quiz Creator/index.md
> +<!-- - [GitHub]() -->
Please add these links

2023-07-19 18:08 UTC, Apoorvgarg-creator requested changes

2023-07-19 18:08 UTC, Apoorvgarg-creator commented on docs/2023/Quiz Creator/Quiz Creator/updates/2023-07-14.md
> +* Understanding of the proper ways to Raise a PR when working within a organisation
Learnings should be descriptive

2023-07-20 04:15 UTC, Prakhar-commits commented on docs/2023/Quiz Creator/Quiz Creator/index.md
> +<!-- - [GitHub]() -->
Done

2023-07-20 04:15 UTC, Prakhar-commits commented on docs/2023/Quiz Creator/Quiz Creator/index.md
> +Rishabh Jain
Done

2023-07-20 12:13 UTC, wasup-yash commented on docs/2023/Quiz Creator/Quiz Creator/updates/2023-08-04.md
> +author: Rishabh Jain
you need to update you name here too

2023-07-25 14:53 UTC, Prakhar-commits commented on docs/2023/Quiz Creator/Quiz Creator/updates/2023-08-04.md
> +author: Rishabh Jain
okay

2023-07-25 14:53 UTC, Prakhar-commits commented on docs/2023/Quiz Creator/Quiz Creator/updates/2023-07-14.md
> +* Understanding of the proper ways to Raise a PR when working within a organisation
okay

2023-07-25 15:24 UTC, GeekGawd commented
@Prakhar-commits you still have conflicts please resolve them

2023-07-25 15:48 UTC, Prakhar-commits commented
> @Prakhar-commits you still have conflicts please resolve them

These are vercel related conflicts cannot be resolved unless you have write access

2023-07-25 16:03 UTC, wasup-yash approved these changes

2023-07-26 05:39 UTC, merged

2023-07-26 05:40 UTC, GeekGawd commented
Merged with #286