Week 1 and Week 2 updates
Code4GovTech/c4gt-milestones pull request #187
Opened 2023-07-19 17:36 UTC by gupta-arpan

## Project

Name of the project

### Changes

What was updated (new pages, weekly update, etc.)

### Notes

If there are any further notes.

2023-07-23 20:44 UTC, shubhigupta991 requested changes

2023-07-23 20:44 UTC, shubhigupta991 commented on docs/2023/Sunbird inQuiry/Editor to support new type of questions/updates/2023-07-07.md
> +How to navigate a codebase and work on it.
Please elaborate.

2023-07-23 20:44 UTC, shubhigupta991 commented on docs/2023/Sunbird inQuiry/Editor to support new type of questions/updates/2023-07-21.md
> +## Learnings
Add learnings

2023-07-24 04:43 UTC, gupta-arpan commented on docs/2023/Sunbird inQuiry/Editor to support new type of questions/updates/2023-07-07.md
> +How to navigate a codebase and work on it.
Done, kindly review it

2023-07-24 04:44 UTC, gupta-arpan commented on docs/2023/Sunbird inQuiry/Editor to support new type of questions/updates/2023-07-21.md
> +## Learnings
Done, kindly review it.

2023-07-24 08:39 UTC, shubhigupta991 approved these changes

2023-07-24 08:39 UTC, merged