updates for week3
Code4GovTech/c4gt-milestones pull request #212
Opened 2023-07-21 15:12 UTC by NEGRAH-S

## Project

revampTheObsrvSink

### Changes

Added details upon the week3 progress along with some screenshot as a metric of work

2023-07-24 08:57 UTC, NEGRAH-S commented on docs/2023/Sunbird Obsrv/revampTheObsrvSink/updates/2023-07-21.md
> -## Contributions
ok am over it

2023-07-25 07:30 UTC, shubhigupta991 approved these changes

2023-07-25 07:32 UTC, shubhigupta991 requested changes
Build is failing due to some error run on your local system and resolve the error.
Error :  SyntaxError: /home/runner/work/c4gt-milestones/c4gt-milestones/docs/2023/Sunbird Obsrv/revampTheObsrvSink/updates/2023-07-14.md: Identifier directly after number. (16:32)
Error:  Client bundle compiled with errors therefore further build is impossible.
  14 | </ul>
  15 | <h2 {...{"id":"screenshots--videos"}}>{`Screenshots / Videos`}</h2>
> [16](https://github.com/Code4GovTech/c4gt-milestones/actions/runs/5642883541/job/15283635825?pr=212#step:5:17) | <img src="img/10_7.png"width=400px>
     |                                 ^
  17 | <img src="/img/11_7.png"width=400px>
  18 | <h2 {...{"id":"contribution"}}>{`Contribution`}</h2>
  19 | <h2 {...{"id":"learnings"}}>{`Learnings`}</h2>
SyntaxError: /home/runner/work/c4gt-milestones/c4gt-milestones/docs/[20](https://github.com/Code4GovTech/c4gt-milestones/actions/runs/5642883541/job/15283635825?pr=212#step:5:21)23/Sunbird Obsrv/revampTheObsrvSink/updates/2023-07-[21](https://github.com/Code4GovTech/c4gt-milestones/actions/runs/5642883541/job/15283635825?pr=212#step:5:22).md: Unterminated JSX contents. ([22](https://github.com/Code4GovTech/c4gt-milestones/actions/runs/5642883541/job/15283635825?pr=212#step:5:23):16)
  20 | <ul><li>Learnt ES pipeline and its working </li><ul>
  21 | <ul><li>Learnt about ES injestion through kafka </li></ul>
> 22 |     </MDXLayout>
     |                 ^
  [23](https://github.com/Code4GovTech/c4gt-milestones/actions/runs/5642883541/job/15283635825?pr=212#step:5:24) |   )
  [24](https://github.com/Code4GovTech/c4gt-milestones/actions/runs/5642883541/job/15283635825?pr=212#step:5:25) | };
  [25](https://github.com/Code4GovTech/c4gt-milestones/actions/runs/5642883541/job/15283635825?pr=212#step:5:26) | MDXContent.isMDXComponent = true
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

2023-07-25 10:30 UTC, NEGRAH-S commented
done

2023-07-26 04:48 UTC, merged