[init] added Vehicle Tracking doc template under DIGIT
Code4GovTech/c4gt-milestones pull request #22
Opened 2023-07-13 14:07 UTC by achintya-7

## Project
Vehicle Tracker [DIGIT]

### Changes
Added my docs for DIGIT

### Notes
No

2023-07-14 10:49 UTC, photon0205 requested changes

2023-07-14 10:49 UTC, photon0205 commented on yarn.lock
remove this `yarn.lock` file

2023-07-14 17:40 UTC, achintya-7 commented on yarn.lock
yah done

2023-07-15 06:54 UTC, photon0205 approved these changes

2023-07-18 06:01 UTC, closed without merging

2023-07-18 06:01 UTC, Apoorvgarg-creator commented
This PR got merged in authors' different PR