Files-Update
Code4GovTech/c4gt-milestones pull request #23
Opened 2023-07-13 14:08 UTC by sanbit876

## Project

Name of the project

### Changes

What was updated (new pages, weekly update, etc.)

### Notes

If there are any further notes.

2023-07-14 10:54 UTC, photon0205 requested changes

2023-07-14 10:54 UTC, photon0205 commented on yarn.lock
remove this `yarn.lock` file

2023-07-14 12:02 UTC, sanbit876 commented on yarn.lock
Done

2023-07-15 06:57 UTC, photon0205 commented on yarn.lock
Do one thing, download the yarn.lock file from the repo and copy and paste it and after this commit it in, actually I meant to untrack the yarn.lock file and not to completely delete it.

2023-07-15 14:08 UTC, sanbit876 commented on yarn.lock
Made the required changes....please review it

2023-07-15 15:12 UTC, photon0205 approved these changes

2023-07-18 06:02 UTC, Apoorvgarg-creator approved these changes

2023-07-18 06:02 UTC, merged