Weekly updates for week 1,2,3,4 of Theming and configuration
Code4GovTech/c4gt-milestones pull request #263
Opened 2023-07-25 16:11 UTC by Tushar98644

## Project

Theming and configuration

### Changes

What was updated (new pages, weekly update, etc.)

### Notes

If there are any further notes.

@Apoorvgarg-creator Kindly verify

2023-07-26 19:24 UTC, shubhigupta991 requested changes
_category_.json in docs/2023/Sunbird UCI/Theming and configuration folder

2023-07-26 19:24 UTC, shubhigupta991 commented on docs/2023/Sunbird UCI/Theming and configuration/updates/2023-07-07.md
> + #### Link to PR: https://github.com/samagra-comms/uci-web-channel/pull/130
Attatch this link under contribution section

2023-07-26 19:24 UTC, shubhigupta991 commented on docs/2023/Sunbird UCI/Theming and configuration/updates/2023-07-14.md
> + #### Link to PR: https://github.com/samagra-comms/uci-web-channel/pull/130
same.

2023-07-26 19:24 UTC, shubhigupta991 commented on docs/2023/Sunbird UCI/Theming and configuration/updates/2023-07-21.md
> +#### Link to PR: https://github.com/samagra-comms/uci-web-channel/pull/132
same

2023-07-27 05:12 UTC, Apoorvgarg-creator requested changes

2023-07-27 05:12 UTC, Apoorvgarg-creator commented on docs/2023/Sunbird UCI/Theming and configuration/index.md
> +slug: /2023/Sunbird UCI/Tushar Banik
Name must match the path of the file

2023-07-27 05:12 UTC, Apoorvgarg-creator commented on docs/2023/Sunbird UCI/Theming and configuration/updates/2023-07-07.md
> +![](https://i.postimg.cc/BnmLJVM9/Screenshot-2023-07-25-at-9-11-56-PM.png)
Why are there https links ? 
And also appropriate name for files

2023-07-27 13:04 UTC, GeekGawd commented
@Tushar98644 Could you add alt text to it please

2023-08-01 15:45 UTC, GeekGawd commented
@Tushar98644 add the ppt and the mentor feedback also kindly add the alt text to the images please.

2023-08-01 20:22 UTC, Tushar98644 commented
> @Tushar98644 add the ppt and the mentor feedback also kindly add the alt text to the images please.

Done

2023-08-02 10:12 UTC, Apoorvgarg-creator approved these changes

2023-08-02 10:13 UTC, shubhigupta991 approved these changes

2023-08-02 10:17 UTC, merged