[ Beckn in a box ]  Added Week 1 progress
Code4GovTech/c4gt-milestones pull request #306
Opened 2023-07-26 16:23 UTC by premsaivarmachekuri

## Project

BeckN in a box

### Changes

Added my Week 1 Progress

### Notes

WIll be adding my other milestones soon

2023-07-26 19:19 UTC, shubhigupta991 requested changes
Please follow the format

2023-07-27 02:14 UTC, pvsyvarmachekuri commented
> Please follow the format

Can you say the changes to be made

2023-07-27 06:23 UTC, Vivek-Kumar-Shrivastav commented
you have to make two changes:
1. Give your image files a meaningful name, not just "image.png"
2. In each week change the author name by your name.

2023-07-27 10:24 UTC, Vivek-Kumar-Shrivastav commented on docs/2023/BeckN/Beckn in a box/updates/image-1.png
change the image file name

2023-07-27 10:25 UTC, Vivek-Kumar-Shrivastav commented on docs/2023/BeckN/Beckn in a box/updates/image.png
change the image file name

2023-07-27 11:44 UTC, closed without merging