add week 4 updates for warpsql
Code4GovTech/c4gt-milestones pull request #354
Opened 2023-07-29 16:59 UTC by PiyushRaj927

## Project

WarpSQL

### Changes

Week 4 updates

2023-07-29 17:01 UTC, PiyushRaj927 commented
Hi @Apoorvgarg-creator can you review this when you have a chance? Thanks!

2023-07-30 12:21 UTC, Apoorvgarg-creator requested changes

2023-07-30 12:21 UTC, Apoorvgarg-creator commented on docs/2023/WarpSQL/Plugins, Disaster Recovery, Benchmarking/updates/2023-07-28.md
@PiyushRaj927 Please add presentation link

2023-07-30 17:38 UTC, PiyushRaj927 commented on docs/2023/WarpSQL/Plugins, Disaster Recovery, Benchmarking/updates/2023-07-28.md
Done @Apoorvgarg-creator

2023-08-01 16:40 UTC, PiyushRaj927 commented on docs/2023/WarpSQL/Plugins, Disaster Recovery, Benchmarking/updates/2023-07-28.md
> +slide for the midpoint demo showcase: https://docs.google.com/presentation/d/13-oQPURoz-XgenC-2GlqVa7wnSYXmin8/
Done @jayesh212

2023-08-01 16:43 UTC, jayesh212 approved these changes

2023-08-01 16:43 UTC, merged