added week 4 milestones
Code4GovTech/c4gt-milestones pull request #410
Opened 2023-07-31 19:09 UTC by RiddhiG2512

## Project
DIGIT Jurisdiction based workflow

### Changes
Added week 4 milestones

2023-08-01 05:15 UTC, claddyk commented on docs/2023/DIGIT/Jurisdiction Based Workflow/updates/2023-07-28.md
> +      Completed midpoint showcase
```suggestion
- [x] Midpoint demo showcase
- [x] Completed midpoint showcase
```

2023-08-01 05:15 UTC, claddyk commented on docs/2023/DIGIT/Jurisdiction Based Workflow/updates/2023-07-28.md
>  ## Learnings
Please share your learnings also.

2023-08-01 05:16 UTC, photon0205 requested changes
add your learnings and also give access to the ppt to all

2023-08-01 10:31 UTC, RiddhiG2512 commented
Made the requested changes. Please review

2023-08-01 15:57 UTC, shubhigupta991 requested changes
Please add super-mentor feedback

2023-08-09 11:22 UTC, RiddhiG2512 commented
Made changes for week 4 and added week 5 updates

2023-08-09 11:59 UTC, merged