Updated Week 4
Code4GovTech/c4gt-milestones pull request #444
Opened 2023-08-02 16:52 UTC by ShlokRana

## Project

Auto generates questions in QuML

### Changes

Adding the PPT link and the Super Mentor Reviews

### Notes

If there are any further notes.

2023-08-03 10:35 UTC, claddyk commented
Please add the `milestiones` as well the `conntributions` sections apart from the learnings that you've shared.

2023-08-03 11:52 UTC, ShlokRana commented
I have already added the milestones and contributions in the previous PR.

2023-08-07 13:47 UTC, shubhigupta991 requested changes
Please add link of your PPT and super mentor feedback.

2023-08-08 08:58 UTC, shubhigupta991 approved these changes

2023-08-08 08:58 UTC, merged