Week 5 milestones: Telemetry Dashboard
Code4GovTech/c4gt-milestones pull request #488
Opened 2023-08-07 19:25 UTC by psankhe28

## Project

Telemetry Dashboard

### Changes

Week 5 milestones updated

2023-08-07 19:25 UTC, psankhe28 commented
@Apoorvgarg-creator Please review it.

2023-08-08 10:19 UTC, Apoorvgarg-creator requested changes

2023-08-08 10:19 UTC, Apoorvgarg-creator commented on docs/2023/Sunbird UCI/Telemetry Dashboard/updates/2023-08-04.md
@psankhe28 Then remove the headings, don't leave blank

2023-08-08 10:42 UTC, psankhe28 commented on docs/2023/Sunbird UCI/Telemetry Dashboard/updates/2023-08-04.md
I have removed it.

2023-08-08 15:04 UTC, merged