demo update
Code4GovTech/c4gt-milestones pull request #6
Opened 2023-07-13 14:02 UTC by NEGRAH-S

## Project

Sunbird Observe - Revamp the observe sink 

### Changes

 Updated (new pages, weekly update, etc.)

### Notes

N/A

2023-07-13 14:28 UTC, GeekGawd commented
You haven't the folder name Frontend and Deep Linking kindly change it

2023-07-14 05:31 UTC, NEGRAH-S commented
@GeekGawd hey made changes. kindly check and merge.

2023-07-14 06:10 UTC, GeekGawd commented
@NEGRAH-S kindly remove the new folder and keep the folder structure as 2023/Sunbird/project-name, also update the slug to keep it the same name the as the folder names.

2023-07-14 07:13 UTC, NEGRAH-S commented
@GeekGawd can we connect on discord for once

2023-07-14 08:06 UTC, NEGRAH-S commented
@GeekGawd u can check did the final changes

2023-07-14 09:58 UTC, photon0205 requested changes

2023-07-14 09:58 UTC, photon0205 commented on docs/2023/Sunbird Obsrv/revampTheObsrvSink/index.md
> + [Email](negrahsingh32@gmail.com)
change this to `[Email](mailto:negrahsingh32@gmail.com)`

2023-07-14 09:58 UTC, photon0205 commented on docs/2023/Sunbird Obsrv/revampTheObsrvSink/index.md
> +[GitHub](NEGRAH-S)
add full link with https for both github and linkedin

2023-07-14 11:13 UTC, photon0205 approved these changes

2023-07-14 11:56 UTC, NEGRAH-S reviewed
thnx for approval @photon0205 @GeekGawd

2023-07-16 13:37 UTC, claddyk approved these changes

2023-07-16 13:37 UTC, claddyk commented on docs/2023/Sunbird Obsrv/revampTheObsrvSink/index.md
> +[GitHub](https://github.com/NEGRAH-S)
```suggestion
- [Email](mailto:negrahsingh32@gmail.com)
- [Linked In](https://www.linkedin.com/in/negrahs23/) 
- [GitHub](https://github.com/NEGRAH-S) 
```

2023-07-16 13:37 UTC, merged