Created my project folder in cQube Folder
Code4GovTech/c4gt-milestones pull request #86
Opened 2023-07-13 15:34 UTC by lohith1392

## Project

Input File Validator

### Changes

Added a new section under the cQube project.

### Notes

If there are any further notes.

2023-07-13 15:37 UTC, lohith1392 commented
can you merge my ps?

2023-07-14 14:07 UTC, claddyk requested changes

2023-07-14 14:07 UTC, claddyk commented on docs/2023/cQube/Input File Validator/index.md
> +
This should be replaced by:
```bash
- [Email](mailto:peddilohith13092002@gmail.com)
- [Linked In](https://www.linkedin.com/in/peddi-lohith-3a0851203/) 
- [GitHub](https://github.com/lohith1392) 
```

2023-07-14 14:24 UTC, lohith1392 commented on docs/2023/cQube/Input File Validator/index.md
> +
made changes can you check it once

2023-07-14 14:24 UTC, claddyk approved these changes

2023-07-14 17:23 UTC, merged