Llm2
Code4GovTech/c4gt-milestones pull request #91
Opened 2023-07-13 18:49 UTC by vanshika230

## Project

LLMs for Question Answering Part 2

### Changes

- Added names in update.md
- Added changes in category.json

### Notes

If there are any further notes.

2023-07-14 08:41 UTC, shubhigupta991 commented
@vanshika230 label needs to be your project name in docs/2023/Karmayogi/LLMs for Question Answering 2/_category_.json file

2023-07-17 05:49 UTC, claddyk requested changes

2023-07-17 05:49 UTC, claddyk commented on docs/2023/Karmayogi/LLMs for Question Answering 2/index.md
> +<!-- - [GitHub](https://github.com/vanshika230)
```suggestion
- [Email](mailto:mvanshika23@gmail.com) 
- [Linked In](https://www.linkedin.com/in/vanshika-mishra2308/) 
- [GitHub](https://github.com/vanshika230) 
```

2023-07-17 05:52 UTC, claddyk commented on docs/2023/Karmayogi/LLMs for Question Answering 2/_category_.json
> +  "label": "Karmayogi",
```suggestion
  "label": "LLMs for Question Answering 1",
```

2023-07-17 05:53 UTC, merged