Added initial BeckN BAP Documentation
Code4GovTech/c4gt-milestones pull request #92
Opened 2023-07-13 19:37 UTC by sandeepB3

## Project
Beckn BAP Boilerplate SDK

### Changes
- [x] Added the folder - BAP Backend SDK & Boilerplate UI
- [x] Initialised the Readme files with necessary informations
- [x] Fixed markdown link url error in a file inside "docs/2023/ODK Extension Collection" folder, since the author didn't use the proper markdown formatting.

### Notes
<img width="1438" alt="Screenshot 2023-07-14 at 12 27 06 AM" src="https://github.com/Code4GovTech/c4gt-milestones/assets/107111616/e826cb04-a8dc-4a48-b2dd-a74390a8522f">

**Error due to wrong markdown formatting: Fixed it**

2023-07-14 08:42 UTC, shubhigupta991 approved these changes

2023-07-14 17:26 UTC, shubhigupta991 requested changes
You need to resolve merge conflicts

2023-07-17 05:57 UTC, claddyk commented
@sandeepB3 I'm closing your PR. You must resolve the connflicts and open a new PR.
If you're unable to do so, then I think it would be better to just delete your local clone of this repo. 
Then again git clone your fork.
And try to implement things step by step. If you still have issues you can refer the recording of the google meet where all this was done and explained by Shruti.

2023-07-17 05:57 UTC, closed without merging

2023-07-17 17:18 UTC, sandeepB3 commented
@claddyk okay, will do.