made changes
Code4GovTech/c4gt-milestones pull request #93
Opened 2023-07-14 03:57 UTC by katakampranavi

created a folder with sunbird-framework-management-ui-tool and also made sufficient changes

## Project

Name of the project

### Changes

What was updated (new pages, weekly update, etc.)

### Notes

If there are any further notes.

2023-07-14 08:28 UTC, simran142002 commented
package lock and yarn has to be reverted

2023-07-14 11:13 UTC, shubhigupta991 requested changes
remove package-lock.json and yarn.lock

2023-07-15 10:34 UTC, katakampranavi commented
@shubhigupta991 please check my commits and approve the PR

2023-07-15 11:49 UTC, shubhigupta991 commented
remove package.json file

2023-07-15 11:52 UTC, shubhigupta991 requested changes
remove the file package.json from git

2023-07-15 12:33 UTC, katakampranavi commented
@shubhigupta991 removed package.json file as suggested

2023-07-17 17:48 UTC, katakampranavi commented
@shubhigupta991 @simran142002 
can anyone please approve my pull request so that i can update my weekly status

2023-07-17 17:54 UTC, shubhigupta991 requested changes
You have not changed the slug line and haven't added your contact details in docs/2023/sunbird-framework-management-ui-tool/index.md file. Please make the following changes

2023-07-17 18:19 UTC, katakampranavi commented
@shubhigupta991 made the changes as suggested. please check and confirm it.

2023-07-18 15:25 UTC, katakampranavi commented
@shubhigupta991, I have made the changes as suggested. please check and confirm it.

2023-07-19 10:25 UTC, katakampranavi commented
@shubhigupta991 @simran142002 can anyone please approve my pull request so that i can update my weekly status.

2023-07-21 06:42 UTC, katakampranavi commented
@shubhigupta991 @simran142002 can anyone please approve my pull request so that i can update my weekly status.

2023-07-21 06:53 UTC, simran142002 commented
Your changes should be in 13 files you probably deleted package.json and yarn file instead of reverting them.

2023-07-21 07:11 UTC, katakampranavi commented
@simran142002 as suggested by @shubhigupta991 i have removed the files kindly let me know what changes I need to do in current files

2023-07-21 07:21 UTC, katakampranavi commented
@simran142002 I'm not getting it can you please elaborate what exactly i need to make changes to merge it in to branch apologies for inconvenience

2023-07-22 10:04 UTC, shubhigupta991 requested changes
Can you elaborate the learnings for all the 3 weeks

2023-07-22 10:04 UTC, shubhigupta991 commented on docs/2023/sunbird-framework-management-ui-tool/updates/2023-07-14.md
> +(https://github.com/Sunbird-Knowlg/sunbird-framework-management-ui-tool/tree/main/sunbird-framework-management-tool) this is the link after merging PR
Please attach the link of merged PR.

2023-07-22 10:04 UTC, shubhigupta991 commented on docs/2023/sunbird-framework-management-ui-tool/index.md
> +[Linked In](https://www.linkedin.com/in/pranavi-katakam35)
I have edited this link as this was incomplete. Please take a note for next time

2023-07-25 15:01 UTC, GeekGawd commented
@katakampranavi Your folder structure is wrong, it should be like `organisation_name/project_name`

2023-07-26 05:25 UTC, GeekGawd commented
@katakampranavi Have asked for some changes and also put folder inside Sunbird Knowldg right now its outside

2023-07-26 08:56 UTC, katakampranavi commented
@GeekGawd i didnt get you .can you please elaborate it

2023-07-26 19:10 UTC, shubhigupta991 approved these changes

2023-07-26 19:15 UTC, merged