c4gt-milestones: Add updates
Code4GovTech/c4gt-milestones pull request #94
Opened 2023-07-14 05:42 UTC by jayanth-kumar-morem

2023-07-14 05:56 UTC, Apoorvgarg-creator approved these changes

2023-07-14 05:56 UTC, Apoorvgarg-creator commented on docs/2023/DDP/Set up a monitoring system/index.md
> +[Linked In](https://www.linkedin.com/in/jayanth-kumar-14a4811b5/)
```suggestion
- [LinkedIn](https://www.linkedin.com/in/jayanth-kumar-14a4811b5/)
```

2023-07-14 08:23 UTC, Shruti3004 requested changes

2023-07-14 08:23 UTC, Shruti3004 commented on docs/2023/DDP/Set up a monitoring system/index.md
> +[GitHub](github.com/jayanth-kumar-morem)
- [GitHub](https://github.com/jayanth-kumar-morem)

2023-07-14 08:24 UTC, Shruti3004 commented on docs/2023/DDP/Set up a monitoring system/index.md
> +[GitHub](github.com/jayanth-kumar-morem)
Write https:// in front of your GitHub username

2023-07-17 06:05 UTC, claddyk requested changes

2023-07-17 06:05 UTC, claddyk commented on docs/2023/DDP/Set up a monitoring system/index.md
> +[GitHub](github.com/jayanth-kumar-morem)
```suggestion
- [Email](mailto:jayanthkumar1903@gmail.com)
- [LinkedIn](https://www.linkedin.com/in/jayanth-kumar-14a4811b5/)
- [GitHub](https://github.com/jayanth-kumar-morem)
```

2023-07-17 06:06 UTC, merged